source 'https://rubygems.org'
ruby '>=3.2'

gem 'jekyll', '>=4.3.2'
gem 'jekyll-datapage-generator'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-tidy'
gem 'html-proofer'
gem 'csv'
gem 'logger'
gem 'base64'
